sudo: required
language: c
compiler: gcc
matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgnome-keyring-dev
            - icnsutils
            - graphicsmagick
            - xz-utils
            - libewf-dev
            - libssl-dev
            - libsqlite3-dev
            - libboost-dev
            - libicu-dev
            - libtool
            - sleuthkit
    - os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
            - libewf
            - afflib
            - sleuthkit
            - bulk_extractor
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone --recursive https://github.com/timothyryanwalsh/bulk_extractor && cd bulk_extractor && chmod 755 bootstrap.sh && ./bootstrap.sh && ./configure && make && sudo make install && cd ..; fi
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe
  - sudo pip install --upgrade virtualenv && virtualenv -p python3 env
  - source env/bin/activate && cd src/main && pip install -r backend/requirements.txt && pyinstaller backend/br_processor.py --distpath backend_dist
  - yarn install
script:
  - python backend/test.py && yarn run build
branches:
  only:
  - master
  - prerelease
