---
name: "Build"
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install bulk_extractor and dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo add-apt-repository ppa:ubuntu-toolchain-r/test
              sudo apt-get update && sudo apt-get install -y \
                git \
                g++-7 \
                libgnome-keyring-dev \
                icnsutils \
                graphicsmagick \
                xz-utils \
                libewf-dev \
                libssl-dev \
                libsqlite3-dev \
                libboost-dev \
                libicu-dev \
                libtool \
                sleuthkit
              git clone --recursive https://github.com/tw4l/bulk_extractor && cd bulk_extractor && chmod 755 bootstrap.sh && ./bootstrap.sh && ./configure && make && sudo make install && cd ..
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install libewf afflib sleuthkit bulk_extractor
          fi
        shell: bash
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip requirements
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pip requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r src/main/backend/requirements.txt
      - name: Build backend executable with pyinstaller
        run: |
          pyinstaller src/main/backend/br_processor.py --distpath src/main/backend_dist
      - name: Install node, npm and yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install yarn packages
        run: |
          yarn install
      - name: Build electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prerelease'
        run: |
          yarn run build
      - name: Build and release electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prerelease'
        run: |
          yarn run build --publish always
