---
name: "Test"
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install bulk_extractor and dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo add-apt-repository ppa:ubuntu-toolchain-r/test
              sudo apt-get update && sudo apt-get install -y \
                git \
                g++-7 \
                libgnome-keyring-dev \
                icnsutils \
                graphicsmagick \
                xz-utils \
                libewf-dev \
                libssl-dev \
                libsqlite3-dev \
                libboost-dev \
                libicu-dev \
                libtool \
                sleuthkit
              git clone --recursive https://github.com/tw4l/bulk_extractor && cd bulk_extractor && chmod 755 bootstrap.sh && ./bootstrap.sh && ./configure && make && sudo make install && cd ..
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install libewf afflib sleuthkit bulk_extractor
          fi
        shell: bash
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip requirements
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pip requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r src/main/backend/requirements.txt
      - name: Run tests
        run: |
          python src/main/backend/test.py
